const TEMPLATES = {
	en: [
		{
			title: "PIC-NIC",
			tale: `I remember that time when I @verb:past@ a person. It was a @adjective@ day and I was @verb:participle@ with @1#proper noun@.  We had decided to have a picnic and so we brought everything we needed: a @adjective@ tablecloth, plates, cutlery and glasses of @noun@; and to eat pizzas, a @noun@, some @noun@ and a @noun@. @1#proper noun@ @verb:past@ on the ground and started @verb:participle@ @adverb@. We were in a @adjective@ grove and nobody was there. We @verb:past@ a lot, and we were eating the last pizza. They had already eaten @number@ slices, so the last one was mine. @1#proper noun@ pointed to me and exclaimed: "Look, a @noun@!" And I, @adjective@, turned around @adverb@, but there was nothing. When I turned back, I saw him eating my last slice of pizza! I @verb:past@ the first object at hand, which was a @noun@ and I stuck it in the @noun@. @1#proper noun@ @verb:past@ and fell to the @adjective@ ground. @adverb@, I dug a hole and threw my friend's @adjective@ body into it and went off pretending nothing happened. NO ONE CAN TOUCH MY PIZZA!`
		},
		{
			title: "LETTER FROM AFAR",
			tale: `Dear @proper noun@,<br>I miss you so much and I would like to be with you now. Here it is truly @adjective@. @number@ @time period:plural@ have passed since the last time we @verb:past@. Here the days go by @adverb@ and if it weren't for my @adjective@ job I wouldn't be here. The weather here is always @adjective@ and people behave @adverb@. Yesterday, for example, a person @verb:past@ me and yelled at me: "@verb@, @noun@!", Even if I hadn't done anything.<br> My work here is quite @adjective@, a week ago I @verb:past@ a @noun@ of @noun@ and they complimented me. I met the only nice person here, his name is @proper noun@ and he is a @adjective@ boy.<br> They told me that I can @verb@ again in @number@ days, I can't wait! I miss my house a lot and I will be finally able to @verb@ it.
			Your @adjective@ @proper noun@`
		},
		{
			title: "COMPETITION",
			tale: "I am so @adjective@, I can't wait to start. I am a @noun@! I have @verb:past@ for so much time. The leading competitor is @proper noun@, a @adjective@ man with @number@ @noun:plural@ in place of the @noun@ and he is at @number@ points. <br>Suddenly I hear my name called from the @noun@. It's my turn to @verb@.<br> I @verb@ the @noun@. They give me @noun:plural@ to throw. I throw them and I realize too late that the wind makes @verb@ the arrow to the target. I throw the remaining ones, but I don't @verb@ @noun:plural@.<br> Finally, after the count of the @noun:plural@, I finished @number@th.<br> Not bad, better than @proper noun@. With a @noun@ he @verb:past@ @adverb@ a judge.<br> At the next tournament I will @verb@!",
		},
		{
			title: "VIRTUAL TRAINING",
			tale: "Welcome @1#proper noun@ to the Legend of @noun@ tutorial. In this @adjective@ game, your goal will be to @verb@ the @adjective@ princess, in the @construction@ of the @place@'s @biome@ and to @verb@ all the enemies that will appear before you, using your @adjective@ skills. <br> From now on I will be your thorn in the side, you will not be able to @verb@ without me telling you how. You won't be able to @verb@ without feeling my breath on your neck. <br> I @adverb@ see that you have chosen the @craft@ class. This will give you the opportunity to perform the following moves: \"@action@ of the @adjective@ @noun@\", the \"@action@'s @noun@\", and \"@adjective@ @noun@\".<br> You will also have a natural predisposition in handling @noun:plural@. <br> In the @noun@ market and wherever you are, you will always know which direction the closest @noun@ is. <br> The challenge will not be easy. @number@ pitfalls are hiding around every corner, and many have tried before you, but no one has ever managed to complete the mission. But thanks to your @adjective@ knowledge, you will be able to triumph @adverb@.<br> Good luck, @1#proper noun@! Remember that your number of lives is @adjective@. <br>Try not to @verb@, and to return @adjective@."
		},
		{
			title: "GET OUT OF MY MEADOW!",
			tale: "It was a @adjective@ and @adjective@ @period of the year@ day, the sun was @verb:participle@ on the @noun:plural@ and @proper noun@ @verb:past@ @adverb@. At one point he heard the sounds of children playing with @noun:plural@ in his garden. He had certainly not spent @number@ @time period@ fighting @adverb@, to then be invaded by some kids. <br> He was so @adjective@ that he decided to call the police. A @adjective@ voice replied:<br> \"@city@ police station, how can I help you?\"<br> \"Some thugs have @verb:past@ my garden\"<br> \"Mr. @surname@, you cannot call us every time children play in your garden. Goodbye\"<br> So, with his brain clouded by the fumes of the @substance@, he took his @weapon@, and went out to seek justice.<br>He still remembered his training, using @noun:plural@ to cover himself, and trying not to be seen by enemies. He sent his @animal@ to @verb@ the neighborhood, and found that the children were @verb:participle@ near the vegetable garden. <br> He remembered his youth when he @verb:past@ @nationality:plural@ for fun.<br>It was time to put an end to it, he took aim, and @verb:past@ a child in the @part of the body@. While the others @verb:past@ @adverb@, he lit a @flavor@ cigar, and returned to play @videogame@."
		},
		{
			title: "THE MARRIAGE",
			tale: "Here I am. How many @adjective@ choices have led me to this moment. <br> My witness @proper noun@ was at my side, visibly @adjective@. He is convinced that I shouldn't marry @proper noun@, he thinks she's a @noun@ since he first met her. <br> Then suddenly the notes of the @musical band@ wedding march leave, and everyone gets to their feet, and she is there, @adjective@ as ever, followed by two @noun:plural@, who hold her the ends of her @noun@.<br> \"Now, or never again,\" my friend whispered to me. He was almost beginning to convince me. Was I making a choice that I would soon regret? <br> It seemed like a @pariod of time@ had passed, and the bride joined us at the @noun@. Father @proper noun@ took a @noun@ and began the ritual that would bind me forever to her. <br> I looked at my father. That @noun@ was only there for the aperitif. I was already seeing him @verb:participle@ the wedding cake. My mother kept @verb:participle@, she was consuming more handkerchiefs than a @noun@. <br> It was almost a miracle, the ceremony was interrupted by a loud noise. We all turned to the entrance. There, the @noun@ @verb:past@ in the church, upsetting everyone present. <br> I was stunned to see the bride pulling a @noun@ from under her dress which she swung to make her way through the crowd.<br>There was a general uproar, @noun:plural@ were also brought in. Those present were now @verb:participle@ in panic.<br> @adverb@, I hid under the @noun@. The priest drew a @noun@ from under the cassock, and @verb:past@ the damsel. <br> I was @adjective@, but relieved. He was evidently an undercover @noun@. And I was going to marry a @noun@.<br>	What a @adjective@ day."
		},
		{
			title: "BBQ WITH FRIENDS",
			tale: "You cannot imagine my @noun@ when I discovered that I had finally obtained my @verb:participle@ license. So much so that I decided to celebrate with a @adjective@ barbecue.<br>For the occasion, therefore, I invited my @adjective@ friends to my house. Everything was ready: the meat was marinating @adverb@ in the @noun@, while the fridge was overflowing with @noun@ cans.<br> As @noun:plural@ arrived, the @noun@ also filled up the dishes, and the environment warmed up @adverb@.<br></br> @proper noun@ and I, to fuel the fire, threw @noun:plural@ in the flames, with nothing short of @adjective@ results.<br>We were all a bit busy with something. My mother insisted on @verb:participle@ the sauces. To such kindness I certainly could not refuse.<br> @proper noun@ instead wanted to bring his specialty at all costs: @noun:plural@ of @noun@ with @noun@.<br> The @adjective@ girls, on the other hand, were grappling with the most @adjective@ outlines I had ever seen. From what I understood they were preparing a salad of @noun@ and @noun@ and they had also started to peel @noun:plural@ to be grilled. While the embers @verb:plural@ @adverb@ I could dedicate myself to studying the @noun@: I could not wait to taste it.<br> In short, it was a very @adjective@ afternoon, and we ate like @adjective@ @noun:plural@."
		},
		{
			title: "AT THE ZOO",
			tale: "After standing in line for @number@ @time period: plur.@ Little @proper name@ and his mom walked @adverb@ into the zoo. <br> The baby was @adjective@, and ran @adverb@ to the @animal@ enclosure, which were his favorite animal, so @adverb@ that his mother saw him disappear in the crowd. <br> «@curse@» the mother exclaimed, and shouting @adverb@ his name, she began to @verb@. A zookeeper ran @adverb@ to help, and soon the boy was spotted in the @animal:plural@'s @noun@. A @adjective@ male specimen had @verb: part. past.@ in its @noun@. <br> Rescue attempts started @adverb@. First they tried to lure the beast with @noun:plural@, then with @adjective@ music @musical genre@. All these attempts failed @adverb@. It was time to use the @noun@. <br> With @adjective@ aim the zookeeper hit the animal in the @body part@. The child was thus able @verb@ out of the cage and save himself. <br> The mother, however, as punishment gave him a @noun@ on the @part of the body@, thus getting a complaint from the son and ending up in jail for @number@ @time period@."
		}
	],
	it: [
		{
			title: "FUORI DAL MIO PRATO!",
			tale: "Era una tranquilla e @aggettivo:fem. sing.@ giornata di @periodo dell'anno@. Il sole @verbo:ind. impf. III p.s.@ sui @sostantivo:plur.@, e @nome proprio@ @verbo:ind. impf. III p.s.@ @avverbio@. <br> Ad un certo punto avvertì dei bambini che giocavano con dei @sostantivo:plur.@. Non aveva certo passato @numero@ @periodo di tempo:plur.@ a combattere in @nazione@ per poi farsi invadere da quattro ragazzetti. Era così @aggettivo@ che decise di chiamare la polizia.<br> «Commissariato di polizia di @luogo@, come posso aiutarla?»<br>«Dei teppisti hanno @verbo:part. pass.@ la mia proprietà!»<br>«Signor @cognome@, non può chiamarci ogni volta che dei bambini giocano nel suo prato. Arrivederci»<br> Così, con il cervello @aggettivo@ dai fumi del @sostanza@, prese il suo @arma@, e uscì per cercare giustizia.<br> Ricordava ancora il suo addestramento: usare @sostantivo:plur.@ per coprirsi e non farsi vedere dal nemico.<br>Mando il suo @animale@ a @verbo@ le vicinanze, e scoprì che i bambini stavano @verbo:gerundio@ vicino all'orto. Si ricordava la sua giovinezza, quando @verbo:ind. impf. III p.s.@ @nazionalità:plur.@ per divertimento. Lo chiamavano il @mestiere@ di @città@.<br> Era il momento di chiudere la questione: prese la mira e @verbo: ind. pass. rem. III p.s.@ un bambino nel @parte del corpo@. Mentre cadeva @aggettivo@, il suo urlo @verbo: ind. pass. rem. III p.s.@ le orecchie del nostro eroe.<br>Mentre gli altri @verbo:ind. impf. III p.p.@ @avverbio@, lui si accese un sigaro al @sapore@, e se ne tornò a giocare a @(video)gioco@."
		},
		{
			title: "ADDESTRAMENTO VIRTUALE",
			tale: "Benvenuto @1#nickname@ al tutorial di Legend of @parola inglese@. In questo gioco @aggettivo@ il tuo obiettivo sarà @verbo@ la principessa @aggettivo:fem. sing.@ nel @costruzione@ del @bioma@ del @luogo@ e @verbo@ tutti i nemici che ti si pareranno davanti utilizzando le tue @aggettivo:fem. plur.@ abilità.<br> Da questo momento in poi sarò la tua spina nel fianco, non potrai @verbo@ senza che io ti dica come fare, non potrai @verbo@ senza sentire il mio fiato sul collo.<br> Vedo @avverbio@ che hai scelto la classe @mestiere@: questo ti darà la possibilità di eseguire le seguenti mosse @azione@ di @materiale@, @azione@ del @animale@, e @catastrofe naturale@ @aggettivo@. Inoltre avrai una predisposizione naturale nel manovrare @sostantivo:plur.@. Nel commercio di @sostantivo:plur.@ e ovunque ti troverai saprai sempre dove si trova il @sostantivo@ più vicino.<br>La sfida non sarà facile @1#nickname@, @numero@ insidie si nascondono dietro ogni angolo. In molti hanno provato prima di te, ma nessuno è mai riuscito a portare a termine l'impresa. Ma grazie alle tue @aggettivo:fem. plur.@ conoscenze, riuscirai a trionfare @avverbio@.<br>Buona fortuna @1#nickname@. Ricorda che il tuo numero di vite è @aggettivo@. Cerca di non @verbo@ e cerca di tornare @aggettivo@."
		},
		{
			title: "VISITA ALLO ZOO",
			tale: "Dopo essere stati in fila per @numero@ @periodo di tempo:plur.@ il piccolo @nome proprio@ e la sua mamma entrarono  @avverbio@ allo zoo.<br> Il bimbo era @aggettivo@, e corse @avverbio@ al recinto dei @animale:plur.@, che erano il suo animale preferito, così @avverbio@ che la madre lo vide scomparire tra la folla. <br> «@imprecazione@» esclamò la madre, e gridando @avverbio@ il suo nome, cominciò a @verbo@. Una guardia dello zoo accorse @avverbio@ in aiuto, e in breve tempo l'infante venne avvistato nel @sostantivo@ dei @animale:plurale@. Un @aggettivo@ esemplare maschio aveva @verbo:part. pass.@ nel suo @sostantivo@.<br>I tentativi di salvataggio iniziarono @avverbio@. Prima cercarono di attirare la bestia con dei @sostantivo:plurale@, poi con della musica @genere musicale@ @aggettivo:fem. sing.@. Tutti questi tentativi fallirono @avverbio@. Era giunto il momento di usare il @sostantivo@.<br>Con una @ggettivo:fem. sing.@ mira il guardiano dello zoo colpì l'animale nel @parte del corpo@. Il bambino poté così @verbo@ fuori dalla gabbia e salvarsi.<br>La madre però per punizione gli diede un @sostantivo@ sul @parte del corpo@, beccandosì così una denuncia da parte del figlio e finendo in galera per @numero@ @periodo di tempo: plur.@."
		}
	]
};